<?php
$this->headTitle('Log in');

$this->mainMenu()->setActiveItemId('login');

$form->get('username')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Username',
  'required' => true,
  'autofocus' => true
])
  ->setLabelAttributes([
  'class' => 'sr-only'
]);

$form->get('password')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Password',
  'required' => true,
])
  ->setLabelAttributes([
  'class' => 'sr-only'
]);
$form->get('remember_me')->setAttributes([
  'class' => 'form-check-input'
]);
?>
<?= $this->form()->openTag($form); ?>
  <h2 class="form-signin-heading">Please sign in</h2>
  <?php if ($isLoginError) : ?>
  <div class="alert alert-warning" role="alert">
    Incorrect login and/or password.
    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
  </div>
  <?php endif; ?>
  <div class="form-group">
    <?= $this->formLabel($form->get('username')); ?>
    <?= $this->formElement($form->get('username')); ?>
  </div>
  <div class="form-group">
    <?= $this->formLabel($form->get('password')); ?>
    <?= $this->formElement($form->get('password')); ?>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <?= $this->formElement($form->get('remember_me')); ?> Remember me
    </label>
  </div>
  <?= $this->formElement($form->get('redirect_url')); ?>
  <?= $this->formElement($form->get('csrf')) ?>
  <button class="btn btn-primary btn-block" type="submit">Sign in</button>
</form>

<?= $this->form()->closeTag(); ?>
