<?php
$this->headTitle('Add Athor');

$this->mainMenu()->setActiveItemId('authors');

$this->pageBreadcrumbs()->setItems([
  'Home' => $this->url('home'),
  'Manage Authors' => $this->url('authors'),
  'Add Athor' => $this->url('authors', ['action' => 'add'])
]);

$form->get('name')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'George R.R. Martin'
]);

$form->get('books')->setAttributes([
  'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<h1>Add Author</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('books')); ?>
            <?= $this->formElement($form->get('books')); ?>
            <?= $this->formElementErrors($form->get('books')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

