<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>

<h1>Manage Users</h1>

<p>
<a class="btn btn-primary" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
    <span class="oi oi-plus" aria-hidden="true"></span> New User
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Username</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Role(s)</th>
        <th>Date Created</th>
        <th>Status</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($users as $user): ?>

    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getUsername()); ?>
            </a>
        </td>
        <td>
            <?= $this->escapeHtml($user->getEmail()); ?></a>
        </td>
        <td>
            <?= $this->escapeHtml($user->getFullName()); ?></a>
        </td>
        <td>
            <?= $this->escapeHtml($user->getRolesAsString()); ?></a>
        </td>
        <td><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('users',
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="oi oi-pencil" ></span> Edit
            </a>
            <a class="btn btn-primary" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                <span class="oi oi-x"></span> Change Password
            </a>
        </td>
    </tr>

    <?php endforeach; ?>

</table>

