<?php
$this->headTitle('Reset Password');

$form->get('email')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Email address'
]);

$form->get('captcha')->setAttributes([
  'class' => 'form-control',
]);

$form->get('submit')->setAttributes([
  'class' => 'btn btn-primary'
]);

$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<h2>Reset Password</h2>

<p>Enter your e-mail address below to reset your password</p>

<div class="form-group">
<?= $this->formElement($form->get('email')); ?>
<?= $this->formElementErrors($form->get('email')); ?>
</div>
<div class="form-group">
<p class="hint">Enter the letters below as you see them.</p>
<?= $this->formElement($form->get('captcha')); ?>
</div>
<?= $this->formElement($form->get('csrf')); ?>
<?= $this->formElement($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
