<?php
$this->headTitle('Sign up');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
  'Home' => $this->url('home'),
  'Manage Users' => $this->url('users'),
  'Add User' => $this->url('users', ['action' => 'add'])
]);

$form->get('username')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'bachdx'
]);

$form->get('email')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'name@example.com'
]);

$form->get('full_name')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Bach Dang'
]);

$form->get('password')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Enter password',
]);

$form->get('confirm_password')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Retype password',
]);

$form->get('birthday')->setAttributes([
  'class' => 'form-control',
]);

$form->get('gender')->setAttributes([
  'class' => 'form-control',
]);

$form->get('submit')->setAttributes([
  'class' => 'btn btn-primary',
  'value' => 'Sign up',
]);

$form->prepare();
?>

<h1>Add User</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
  <?= $this->formLabel($form->get('username')); ?>
  <?= $this->formElement($form->get('username')); ?>
  <?= $this->formElementErrors($form->get('username')); ?>
</div>

<div class="form-group">
  <?= $this->formLabel($form->get('email')); ?>
  <?= $this->formElement($form->get('email')); ?>
  <?= $this->formElementErrors($form->get('email')); ?>
</div>

<div class="form-group">
  <?= $this->formLabel($form->get('full_name')); ?>
  <?= $this->formElement($form->get('full_name')); ?>
  <?= $this->formElementErrors($form->get('full_name')); ?>
</div>

<div class="form-group">
  <?= $this->formLabel($form->get('birthday')); ?>
  <?= $this->formElement($form->get('birthday')); ?>
  <?= $this->formElementErrors($form->get('birthday')); ?>
</div>

<div class="form-group">
  <?= $this->formLabel($form->get('gender')); ?>
  <?= $this->formElement($form->get('gender')); ?>
  <?= $this->formElementErrors($form->get('gender')); ?>
</div>

<div class="form-group">
  <?= $this->formLabel($form->get('password')); ?>
  <?= $this->formElement($form->get('password')); ?>
  <?= $this->formElementErrors($form->get('password')); ?>
</div>

<div class="form-group">
  <?= $this->formLabel($form->get('confirm_password')); ?>
  <?= $this->formElement($form->get('confirm_password')); ?>
  <?= $this->formElementErrors($form->get('confirm_password')); ?>
</div>

<?= $this->formElement($form->get('submit')); ?>

<?= $this->form()->closeTag(); ?>
