<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
  'Home' => $this->url('home'),
  'Manage Users' => $this->url('users'),
  'View User' => $this->url('users', ['action' => 'view', 'id' => $user->getId()])
]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User <?= $this->escapeHtml($user->getUsername()) ?></h1>


<?php if ($this->access('profile.any.manage') || $this->access('profile.own.manage', ['user' => $user])) : ?>
<p>
    <a class="btn btn-default" href="<?= $this->url(
                                      'users',
                                      ['action' => 'edit', 'id' => $user->getId()]
                                    ); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit
    </a>
    <a class="btn btn-default" href="<?= $this->url(
                                      'users',
                                      ['action' => 'change-password', 'id' => $user->getId()]
                                    ); ?>">
        <span class="glyphicon glyphicon-asterisk"></span> Change Password
    </a>
</p>
<?php endif ?>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Gender:</th>
                <td><?= $this->escapeHtml($user->getGender()) ?></th>
            </tr>
            <tr>
                <th>Birthday:</th>
                <td><?= $this->escapeHtml($user->getBirthday()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <?php if ($this->access('user.manage')) : ?>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
            <?php endif;
            if ($this->access('role.manage')) : ?>
            <tr>
                <th>Roles:</th>
                <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
            </tr>
            <?php endif ?>
        </table>
    </div>
</div>
