<?php
$title = 'Search';
$this->headTitle($title);
$form->setAttribute('action', $this->url('search'));
$form->setAttribute('class', 'mt-4');
$submit = $form->get('submit');
$q = $form->get('q');
$q->setAttribute('class', 'form-control');
$submit->setAttribute('class', 'btn btn-primary');
?>

<?= $this->form()->openTag($form) ?>
<div class="input-group">
<?= $this->formElement($q); ?>
<span class="input-group-btn">
<?= $this->formElement($submit); ?>
</span>
</div>
<?= $this->form()->closeTag() ?>
<div class="mt-4">
<?php if (isset($results)) {
  if (count($results) == 0) { ?>
	<p class="border border-danger rounded w-100 px-3 py-2 text-danger"> No result found </p>
  <?php } else { ?>
  <div class="list-group w-100">
	<?php foreach ($results as $result) { ?>
    <a href="<?= $this->url('manage', ['action' => 'view', 'id' => $result->id]) ?>" class="list-group-item list-group-item-action d-sm-flex align-items-start">
    <img src="<?= $result->image ?>" height="100" width="100" alt="image">
    <div class="ml-3">
    <h3 class="mb-1 text-primary"><?= $result->name ?></h3>
    <p class="mb-1 text-success"><?= '$'.$result->price ?></p>
    </div>
    </a>
  <?php } ?>
  </div>
<?php
}
} ?>

</div>
