<?= $this->doctype() ?>

  <html lang="en">

  <head>
    <meta charset="utf-8">
      <?= $this->headTitle('Bookstore')->setSeparator(' - ')->setAutoEscape(false) ?>

      <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
      ?>

      <!-- Le styles -->
      <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/open-iconic-bootstrap.css'))
      ?>

      <!-- Scripts -->
      <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.2.1.slim.min.js'))
        ->prependFile($this->basePath('js/popper.min.js'))
      ?>
  </head>

  <body>
    <!-- Navigation bar -->
    <?php
    // Check if the activeMenuItemId passed to layout view model
    // and if so, use it for setting active navbar item.
    if (isset($activeMenuItemId)) {
      $this->mainMenu()->setActiveItemId($activeMenuItemId);
    }
    // Render the navbar
    echo $this->mainMenu()->render();
    ?>
    <div class="container">
      <div class="py-5">
        <div>
          <!-- Breadcrumbs -->
          <?= $this->pageBreadcrumbs()->render(); ?>
        </div>
        <div>
          <!-- Page content placeholder -->
          <?= $this->content; ?>
        </div>
        <hr>
        <footer>
          <p>&copy; 2005 -
            <?= date('Y') ?> by Your Company. All rights reserved.</p>
        </footer>
      </div>
    </div>
    <?= $this->inlineScript() ?>
  </body>

  </html>
