<div class="list-group-item list-group-item-action flex-column align-items-start">
<div class="row">
<div class="col-2">
<img src="<?= $this->item['image'] ?>" width="100px" height="100px">
</div>
<div class="col">
<h5 class="mb-1"><?= $this->item['name'] ?></h5>
</div>
<div class="col-2">
<?php
$this->element->setAttribute('class','form-control');
$this->element->setValue($this->item['quantity']);
?>
<?= $this->formElement($this->element) ?>
</div>
</div>
<p class="mb-1"><?= $this->price ?></p>
</div>
