<div class="list-group w-100">
<div class="list-group-item list-group-item-action d-sm-flex align-items-start">
<img src="<?= $this->item['image'] ?>" width="100px" height="100px">
<div class="mr-auto ml-3">
<h3 class="mb-1 mr-auto"><?= $this->item['name'] ?></h3>
<p class="mb-1 text-success"><?= '$'.$this->item['price'] ?></p>
</div>
<?php
$this->element->setAttribute('class','form-control ml-2');
$this->element->setValue($this->item['quantity']);
?>
<div class="d-flex align-items-baseline">
<?= $this->formLabel($this->element) ?>
<?= $this->formElement($this->element) ?>
</div>
</div>
</div>
