<?php
$this->headTitle('Search');

$this->mainMenu()->setActiveItemId('search');

$this->pageBreadcrumbs()->setItems([
  'Home' => $this->url('home'),
  'Search' => $this->url('books', ['action' => 'search']),
]);
?>

<form>
<div class="input-group" action="<?= $this->url('books', ['action' => 'search']) ?>">
  <select class="form-control" name="type">
    <option value="all">All</option>
    <option value="book">Book Title</option>
    <option value="author">Author Name</option>
  </select>
  <input type="text" name="q" class="form-control w-50">
  <div class="input-group-btn">
    <button type="submit" class="form-control btn btn-primary"><span class="oi oi-magnifying-glass"></span> Search</button>
  </div>
</div>
</form>
