<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Welcome</h1>

<p>
    This is the a website selling books.
</p>

<p>
    Click the <em>Sign in</em> button at the top right. To sign in, use the
    following credentials:
    <ul>
        <li>Username: <em>admin</em></li>
        <li>Password: <em>admin123</em></li>
    </ul>
</p>



